# Generated by Django 5.0.1 on 2024-01-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('cuisine', models.CharField(max_length=200)),
                ('price', models.PositiveBigIntegerField()),
            ],
        ),
    ]
